#!/usr/bin/env node
/**
 * The embedded icon in embodytools.js, against embody_tools_icon.png.
 *
 *   node scripts/icon.mjs            re-embed it (by running the build)
 *   node scripts/icon.mjs --check    exit 1 if they disagree, write nothing
 *
 * embodytools.js is generated by build/assemble.mjs, which reads the PNG and writes
 * the ICON line itself, so re-embedding is just a build. This stays because `npm run
 * icon` is the obvious thing to reach for after changing the art, and because
 * --check is a one-line answer to "is the icon in the shipped file the icon in the
 * repo", which scripts/check.mjs asks on every release.
 */
import { readFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const PLUGIN = join(root, 'embodytools.js');
const ART = join(root, 'embody_tools_icon.png');
const LINE = /^const ICON = 'data:image\/png;base64,[A-Za-z0-9+/=]*';$/m;

export function iconLine() {
	return `const ICON = 'data:image/png;base64,${readFileSync(ART).toString('base64')}';`;
}

if (!process.argv.includes('--check')) {
	execFileSync(process.execPath, [join(root, 'build/assemble.mjs')], { cwd: root, stdio: 'inherit' });
	process.exit(0);
}

const found = readFileSync(PLUGIN, 'utf8').match(LINE);
if (!found) {
	console.error('icon: could not find the ICON line in embodytools.js');
	process.exit(1);
}
if (found[0] === iconLine()) {
	console.log('icon: embodytools.js matches embody_tools_icon.png');
	process.exit(0);
}
console.error('icon: the embedded icon is not embody_tools_icon.png. Run: npm run build');
process.exit(1);
